[package]
name = "bazier_tool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.3", features = ["canvas"]}
iced_native = "0.4"
chrono = "0.4"
